
#load "D:\\code\\fsharp-programming\\fsharp-in-vscode\\.paket\\load\\net6.0\\Microsoft.CodeAnalysis.csx" 
#load "D:\\code\\fsharp-programming\\fsharp-in-vscode\\.paket\\load\\net6.0\\Microsoft.DotNet.Interactive.Documents.csx" 
#load "D:\\code\\fsharp-programming\\fsharp-in-vscode\\.paket\\load\\net6.0\\Microsoft.DotNet.Interactive.Formatting.csx" 
#load "D:\\code\\fsharp-programming\\fsharp-in-vscode\\.paket\\load\\net6.0\\System.Collections.Immutable.csx" 
#load "D:\\code\\fsharp-programming\\fsharp-in-vscode\\.paket\\load\\net6.0\\System.CommandLine.csx" 
#load "D:\\code\\fsharp-programming\\fsharp-in-vscode\\.paket\\load\\net6.0\\System.CommandLine.NamingConventionBinder.csx" 
#load "D:\\code\\fsharp-programming\\fsharp-in-vscode\\.paket\\load\\net6.0\\System.Reactive.csx" 
#load "D:\\code\\fsharp-programming\\fsharp-in-vscode\\.paket\\load\\net6.0\\System.Reflection.Metadata.csx" 
#load "D:\\code\\fsharp-programming\\fsharp-in-vscode\\.paket\\load\\net6.0\\System.Runtime.Loader.csx" 
#load "D:\\code\\fsharp-programming\\fsharp-in-vscode\\.paket\\load\\net6.0\\System.Text.Json.csx" 
#r "C:\\Users\\zhaowei\\.nuget\\packages\\microsoft.dotnet.interactive\\1.0.0-beta.23152.2\\lib\\netstandard2.1\\Microsoft.DotNet.Interactive.dll" 